config/routes.rb
Rails.application.routes.draw do
  get 'reports/comparation_table'

  resources :requirements do
    collection do
      post 'search'
    end
  end

  post 'browser_logs/create'

  resources :teams
  root :to => 'teams#index'

  resources :estimates do
    collection do
      post 'create_round'
    end
  end

  resources :participants do
    member do
      get 'add_to_list'
      get 'confirm_add_to_list'
      get 'remove_from_list'
    end
  end

  resources :rounds

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :team
  belongs_to :requirement
  has_many :rounds
  validates :effort_estimate, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :justification, presence: true
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_requirements_to_estimate
  before_action :set_team
  before_action :set_project
  before_action :set_requirement
  before_action :set_estimate
  before_action :set_round_participants, only: [:index, :create_round]
  before_action :log_access

  # GET /estimates
  def index
    @round = Round.new({estimate:@estimate})
    @round.round_participants = @round_participants
    @estimate_errors = flash[:estimate_errors]
    @estimate_justification = flash[:estimate_justification].present? && (@estimate.justification.nil? || @estimate.justification.empty?) ? flash[:estimate_justification] : nil
    @estimate_effort_estimate = flash[:estimate_effort_estimate].present? && @estimate.effort_estimate.nil? ? flash[:estimate_effort_estimate] : nil
    @estimate.errors.add(:effort_estimate, @estimate_errors.first) if @estimate_errors.present? && @estimate_errors.first.include?('Estimativa final')
    @estimate.errors.add(:justification, @estimate_errors.first) if @estimate_errors.present? && @estimate_errors.last.include?('Justificativa final')
    @is_all_requirements_estimated = is_all_requirements_estimated
  end

  # POST /estimates
  def create
    @estimate = Estimate.new(estimate_params)
    @estimate.team = @team
    respond_to do |format|
      if @estimate.save
        format.html { redirect_to estimates_path({requirement:@estimate.requirement}), notice: 'A estimativa foi salva com sucesso.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /estimates/1
  def update
    @estimate.team = @team
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to estimates_path({requirement:@estimate.requirement}), notice: 'A estimativa foi alterada com sucesso.' }
      else
        format.html { redirect_to estimates_path({requirement:@estimate.requirement}), :flash => {
          estimate_errors: @estimate.errors.full_messages, estimate_effort_estimate: @estimate.effort_estimate,
          estimate_justification: @estimate.justification }}
      end
    end
  end

  def create_round
    @round = Round.new(round_params)
    @round.number = @estimate.rounds.size + 1
    @round.round_participants = @round_participants
    @estimate = @round.estimate
    @requirement = @estimate.requirement
    if @round.save
      redirect_to estimates_path({requirement:@estimate.requirement})
    else
      render :index
    end
  end

  private
    def set_estimate
      @estimate = Estimate.where({team:@team, requirement:@requirement}).last
      unless @estimate
        @estimate = Estimate.new
        @estimate.team = @team
        @estimate.requirement = @requirement
        @estimate.save(validate: false)
      end
    end

    def estimate_params
      estimate_params = params.require(:estimate).permit(:team_id, :requirement_id, :effort_estimate, :justification)
      estimate_params[:effort_estimate].gsub!(',','.')
      estimate_params
    end

    def round_params
      params.require(:round).permit(:estimate_id)
    end

    def set_requirements_to_estimate
      @requirements_to_estimate = Requirement.where(for_experiment: true)
    end

    def set_requirement
      @requirement = params[:estimate].nil? || params[:estimate][:requirement_id].nil? ?
        Requirement.find(params[:requirement]) :
        Requirement.find(estimate_params[:requirement_id]) rescue nil
    end

    def set_team
      begin
        @team = Team.find(session[:team_id])
      rescue
        redirect_to teams_path
      end
    end

    def set_project
      @project = Requirement.where(for_experiment: true).first.project
    end

    def set_round_participants
      @round_participants = []
      if params[:round_participants].present?
        params.require(:round_participants).each do |param_round_participant|
          round_participant_params = param_round_participant.permit(:participant_id,:effort_estimate,:justification)
          round_participant_params[:effort_estimate] = round_participant_params[:effort_estimate].gsub(',','.')
          @round_participants << RoundParticipant.new(round_participant_params)
        end
      else
        @team.participants.each do |participant|
          @round_participants << RoundParticipant.new({participant:participant})
        end
      end
    end

    def is_all_requirements_estimated
      (0 == @requirements_to_estimate.count -
        Estimate.where({team:@team, requirement:@requirements_to_estimate}).where('effort_estimate IS NOT NULL AND effort_estimate > 0').count)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<p>
  <strong>
    Quanto tempo do cronograma total do projeto foi gasto antes do início da execução desta atividade:
  </strong>
  <%= (@requirement.relative_starting_point * 100).round(2) %>%.
</p>
<p>
  <strong>
    Quanto do projeto já foi entregue antes do início da execução desta atividade:
  </strong>
  <%= (@requirement.relative_completeness * 100).round(2) %>%.
</p>
<p>
  <strong>Descrição:</strong><br />
  <%= @requirement.description.strip.gsub("\n",'<br />').html_safe %>
</p>
<br />
<% if(@estimate.new_record? || @estimate.effort_estimate.nil? || @estimate.justification.empty?) %>
  <%= render 'new_round' %>
  <div class="final-estimate" <%= @estimate_errors ? '' : 'style="display:none"'.html_safe %>>
    <% if @estimate_errors.present? %>
      <div id="error_explanation">
        <h2>Os erros abaixo impedem esta estimativa de ser gravada:</h2>
        <ul>
          <% if @estimate_errors.any? %>
            <% @estimate_errors.each do |message| %>
              <li><%= message %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%=  %>
    <%= form_for(@estimate) do |e| %>
      <%= e.hidden_field :requirement_id %>
      <p>
        <strong>Estimativa final:</strong>
        <% if @estimate_effort_estimate.nil? %>
          <%= e.text_field :effort_estimate %>
        <% else %>
          <%= e.text_field :effort_estimate, {value: @estimate_effort_estimate} %>
        <% end %>
      </p>
      <p>
        <strong>Descreva livremente, e com o máximo de detalhes as razões e incertezas que o(s) levou(aram) a esta estimativa:</strong><br />
        <div class="allwidth">
          <% if @estimate_justification.nil? %>
            <%= e.text_area :justification %>
          <% else %>
            <%= e.text_area :justification, {value: @estimate_justification} %>
          <% end %>
        </div>
      </p>
      <p class="actions">
        <%= e.submit 'Salvar' %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/estimates/_header.html.erb
<span>Time: "<%= @team.name %>"</span>
<% unless(BLOCK_REQUIREMENTS_INDEX) %>
	<span><%= link_to 'Banco de dados histórico', requirements_path, {target: '_blank'} %></span>
<% end %>
<span><%= link_to 'Sair do experimento', teams_path %></span>
<br clear="both"/>
<br clear="both"/>

app/views/estimates/_list.html.erb
<div style="float:left;margin-right:20px">
  <fieldset>
    <legend>Requisitos a estimar</legend>
    <table>
      <tbody>
        <% @requirements_to_estimate.each_with_index do |requirement, index| %>
          <tr>
            <td>Requisito <%= (index+1) %></td>
            <td><%= link_to 'Abrir', estimates_path({requirement: requirement}) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>
  <% if !BLOCK_RESULTS_INDEX && @is_all_requirements_estimated %>
    <fieldset>
      <legend>Resultados</legend>
      <%= link_to 'Tabela de Comparação', reports_comparation_table_path %>
    </fieldset>
  <% end %>
</div>

app/views/estimates/_new_round.html.erb
<fieldset <%= @estimate_errors ? 'style="display:none"'.html_safe : '' %>>
  <legend>Rodada <%= @estimate.rounds.size + 1 %></legend>
  <%= form_for(@round, url:{action: :create_round}) do |f| %>
    <%= f.hidden_field :estimate_id %>
    <%= hidden_field_tag :requirement_id, @round.estimate.requirement.id %>
    <div id="error_explanation">
      <h2>Os erros abaixo impedem esta estimativa de ser gravada:</h2>
      <ul>
        <% if @round.errors.any? %>
          <% @round.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <table>
      <thead>
        <th>Nome</th>
        <th>Valor Anterior</th>
        <th>Valor Atual</th>
        <th>Valor Justificativa</th>
      </thead>
      <tbody>
        <% @round.round_participants.each_with_index do |round_participant, index| %>
          <%= fields_for 'round_participants[]', round_participant do |rp| %>
            <tr>
              <td>
                <%= rp.hidden_field :participant_id %>
                <%= round_participant.participant.name %>
              </td>
              <td><%= @estimate.rounds.last.round_participants.where(participant: round_participant.participant).last.effort_estimate rescue '' %></td>
              <td><%= rp.text_field :effort_estimate %></td>
              <td><%= rp.text_area :justification %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <p class="actions">
      <%= f.submit 'Terminar rodada' %>
      <% unless @estimate.rounds.empty? %>
        | <%= link_to 'Definir estimativa final', '#', {class: 'close-rounds'} %>
      <% end %>
    </p>
  <% end %>
</fieldset>
<script>
if(jQuery('#error_explanation li').length == 0)
  jQuery('#error_explanation').hide();

var has_shown_error = false;
jQuery('a.close-rounds').click(function(e){
  e.preventDefault();
  var fields = jQuery('#new_round :text:visible,textarea:visible')
  for(var i = 0; i < fields.length; i++){
    if(jQuery(fields[i]).val() != ''){
      if(!has_shown_error) {
        has_shown_error = true;
        jQuery('#error_explanation').show();
        jQuery('#error_explanation ul').append('<li>Termine a rodada antes de definir a estimativa final</li>');
      }
      return;
    }
  }
  jQuery(this).closest('fieldset').hide();
  jQuery('div.final-estimate').show();
});

</script>

app/views/estimates/_project.html.erb
<div>
  <fieldset>
    <legend>Projeto</legend>
    <p>
      <strong>Objetivos do projeto:</strong>
      <%= @project.objective %>.
    </p>
    <p>
      <strong>Tecnologias empregadas:</strong>
      <%= @project.technologies %>.
    </p>
    <p>
      <strong>Tamanho estimado do projeto:</strong>
      <%= @project.size %> homens-hora.
    </p>
  </fieldset>
</div>

app/views/estimates/index.html.erb
<%= render 'header' %>
<%= render 'project' %>
<%= render 'list' %>
<% unless(@requirement.nil?) %>
<div style="float:left;position:absolute;margin-left:180px">
  <fieldset>
    <legend>Requisito <%= (@requirements_to_estimate.index(@requirement)+1) %></legend>
    <p id="notice"><%= notice %></p>
    <%= render 'form' %>
  </fieldset>
</div>
<% end %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @estimate.team %>
</p>

<p>
  <strong>Requirement:</strong>
  <%= @estimate.requirement %>
</p>

<p>
  <strong>Estimate value:</strong>
  <%= @estimate.estimate_value %>
</p>

<p>
  <strong>Justification:</strong>
  <%= @estimate.justification %>
</p>

<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %>