config/routes.rb
Rails.application.routes.draw do
  get 'reports/comparation_table'

  resources :requirements do
    collection do
      post 'search'
    end
  end

  post 'browser_logs/create'

  resources :teams
  root :to => 'teams#index'

  resources :estimates do
    collection do
      post 'create_round'
    end
  end

  resources :participants do
    member do
      get 'add_to_list'
      get 'confirm_add_to_list'
      get 'remove_from_list'
    end
  end

  resources :rounds

end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :project
  has_many :estimates

  def ar estimate
    (self.real_effort - estimate).abs
  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_project_ids
  before_action :log_access
  before_action :set_team
  before_action :look_if_its_blocked

  def index
    @filters = {}
  end

  def search
    @filters = params.permit(:description, :project_id, :real_effort_min, :real_effort_max)
    @requirements = Requirement.where(for_experiment: false)
    @requirements = @requirements.where({project_id: @filters[:project_id]}) if @filters[:project_id].present?
    @requirements = @requirements.where("real_effort >= ?", @filters[:real_effort_min]) if @filters[:real_effort_min].present?
    @requirements = @requirements.where("real_effort <= ?", @filters[:real_effort_max]) if @filters[:real_effort_max].present?
    keywords_order = ''
    if @filters[:description].present?
      description = @filters[:description].clone
      keywords = description.scan(/("[^"]+")+/).collect {|keyword| keyword.first[1..-2]}
      keywords.reject!(&:empty?)
      keywords.each {|keyword| description.gsub!("\"#{keyword}\"",'') }
      description = description.gsub("'",'').gsub('"','')
      keywords.concat(description.scan(/([^ ]+)/).collect {|keyword| keyword.first})
      keywords.reject!(&:empty?)
      keywords_conditions =(keywords.collect {|keyword| "(requirements.description LIKE \"%#{keyword}%\" OR projects.objective LIKE \"%#{keyword}%\" OR projects.technologies LIKE \"%#{keyword}%\")"})
      @requirements = @requirements.where(keywords_conditions.join(' AND '))
      keywords_order = keywords.collect do |keyword|
        ['requirements.description', 'projects.objective', 'projects.technologies'].collect do |field|
          "((LENGTH(#{field}) - LENGTH(REPLACE(#{field}, '#{keyword}', ''))) / #{keyword.size})"
        end.join(' + ')
      end.join(' + ')
      keywords_order += ' DESC,'
    end
    @requirements = @requirements.joins(:project).order("#{keywords_order} projects.title ASC, relative_starting_point ASC")
  end

  def show
    redirect_to requirements_path if params.permit(:id)['id'] == 'search'
    @requirement = Requirement.where(params.permit(:id)).last
  end

  private
  def set_project_ids
    @project_ids = (Project.all.order(title: :asc).reject {|project| project.requirements.where(for_experiment: false).count == 0}).
      collect {|p| ["#{p.title} (#{p.size} homens-hora)",p.id]}
  end

  def set_team
    begin
      @team = Team.find(session[:team_id])
    rescue
      redirect_to teams_path
    end
  end

  def look_if_its_blocked
    redirect_to teams_path if BLOCK_REQUIREMENTS_INDEX
  end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/requirements/_search_fields.html.erb
<fieldset>
  <legend>Filtros de Busca</legend>
  <%= form_tag search_requirements_path, method: :post do %>
    <div class="field">
      <%= label_tag :description, 'Palavras-chave:' %>
      <%= text_field_tag :description, @filters[:description] %>
      *Para buscas com palavras compostas, utilize-as entre aspas duplas.
    </div>
    <div class="field">
      <%= label_tag :project_id, 'Projeto:' %>
      <%= select_tag :project_id, options_for_select(@project_ids, @filters[:project_id]), include_blank: true %>
    </div>
    <div class="field">
      <%= label_tag :real_effort_min, 'Esforço realizado mínimo:' %>
      <%= number_field_tag :real_effort_min, @filters[:real_effort_min], min: 0 %>
    </div>
    <div class="field">
      <%= label_tag :real_effort_max, 'Esforço realizado máximo:' %>
      <%= number_field_tag :real_effort_max, @filters[:real_effort_max], min: 0 %>
    </div>
    <div class="actions">
      <%= submit_tag 'Buscar' %>
    </div>
  <% end %>
</fieldset>

app/views/requirements/index.html.erb
<%= render 'search_fields' %>

app/views/requirements/search.html.erb
<%= render 'search_fields' %>
<fieldset>
  <legend>Resultados da Busca (<%= @requirements.size %> resultados)</legend>
  <table class="projects-table">
    <tr>
      <th>Projeto (homens-hora)</th>
      <th>Momento de Estimativa</th>
      <th>Esforço Realizado</th>
      <th>Descrição</th>
      <th></th>
    </tr>
    <% @requirements.each do |requirement| %>
      <% project = requirement.project %>
      <%= requirement.hashkey if project.nil? %>
      <% next if project.nil? %>
      <tr>
        <td><%= project.title %> (<%= project.size %> homens-hora)</td>
        <td><%= (requirement.relative_starting_point * 100).round(2) %>%</td>
        <td><%= requirement.real_effort %> homens-hora</td>
        <td><%= requirement.description[0,80]+'...' %></td>
        <td><%= link_to 'Abrir', requirement_path(requirement), {target: '_blank'} %></td>
      </tr>
    <% end %>
  </table>
  <script>
    $('.projects-table').on('click', 'a', function(e){
      e.preventDefault();
      $.get($(this).attr('href'), function(data){
        $('.project-show-content').html(data);
        $(document.body).scrollTo('.project-show-content', 0);
      });
    })
  </script>
</fieldset>
<div class="project-show-content"></div>

app/views/requirements/show.html.erb
<fieldset>
  <fieldset>
    <legend>Dados do Projeto</legend>
    <p>
      <strong>Objetivos do projeto:</strong>
      <%= @requirement.project.objective %>.
    </p>
    <p>
      <strong>Tecnologias empregadas:</strong>
      <%= @requirement.project.technologies %>.
    </p>
    <p>
      <strong>Tamanho estimado do projeto:</strong>
      <%= @requirement.project.size %> homens-hora.
    </p>
  </fieldset>
  <fieldset>
    <legend>Dados do Requisito</legend>
    <p>
      <strong>
        Quanto tempo do cronograma total do projeto foi gasto antes do início da execução desta atividade:
      </strong>
      <%= (@requirement.relative_starting_point * 100).round(2) %>%.
    </p>
    <p>
      <strong>
        Quanto do projeto já foi entregue antes do início da execução desta atividade:
      </strong>
      <%= (@requirement.relative_completeness * 100).round(2) %>%.
    </p>
    <p>
      <strong>Esforço realizado:</strong>
      <%= @requirement.real_effort.round(2).to_s %> homens-hora.
    </p>
    <p>
      <strong>Descrição:</strong><br />
      <%= @requirement.description.strip.gsub("\n",'<br />').html_safe %>
    </p>
  </fieldset>
</fieldset>