config/routes.rb
Rails.application.routes.draw do
  get 'reports/comparation_table'

  resources :requirements do
    collection do
      post 'search'
    end
  end

  post 'browser_logs/create'

  resources :teams
  root :to => 'teams#index'

  resources :estimates do
    collection do
      post 'create_round'
    end
  end

  resources :participants do
    member do
      get 'add_to_list'
      get 'confirm_add_to_list'
      get 'remove_from_list'
    end
  end

  resources :rounds

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  acts_as_paranoid
  has_many :competences
  has_many :round_participants
  has_many :rounds, through: :round_participants
  has_many :team_participants
  has_many :teams, through: :team_participants
  validates :name, presence: true
  validates :sex, presence: true
  validates :competences, presence: true
  validates :birthday, timeliness: { before: lambda{Date.current}, type: :date }

  def sex_verbose
    case sex
      when 1 then 'Masculino'
      when 2 then 'Feminino'
      else ''
    end
  end

  def birthday_verbose
  	self.birthday.strftime("%d/%m/%Y") rescue ''
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy, :add_to_list, :confirm_add_to_list, :remove_from_list]
  before_action :set_team
  before_action :set_selected_participants
  before_action :set_competences, only: [:create, :update]
  before_action :expires_now
  before_action :log_access

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all.to_a.delete_if {|participant| @selected_participants.include? participant}
  end

  # GET /participants/new
  def new
    @participant = Participant.new sex: 1, competences: [
      Competence.new({title:'Estimativa de Software',level:1}),
      Competence.new({title:'Java',level:1}),
      Competence.new({title:'Sistemas Operacionais',level:1})]
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)
    @participant.competences = @competence
    respond_to do |format|
      if @participant.save
        TeamParticipant.create(participant: @participant, team: @team)
        format.html { redirect_to participants_url }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    @participant_bkp = Participant.new(@participant.attributes)
    respond_to do |format|
      if @participant.update(participant_params)
        @participant.competences.delete_all
        @competence.each {|competence| competence.participant = @participant; competence.save}
        @participant_bkp.id = nil
        @participant_bkp.original_participant_id = @participant.id
        @participant_bkp.save(validate: false)
        @participant_bkp.delete
        format.html { redirect_to add_to_list_participant_url(@participant), notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_list
    render :add_to_list
  end

  def confirm_add_to_list
    unless @selected_participants.include? @participant
      TeamParticipant.create(participant: @participant, team: @team)
    end
    redirect_to participants_url
  end

  def remove_from_list
    if @selected_participants.include? @participant
      TeamParticipant.find_by(participant_id: @participant.id, team: @team).delete
    end
    redirect_to participants_url
  end

  private
    def set_team
      begin
        @team = Team.find(session[:team_id])
      rescue
        redirect_to teams_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def set_competences
      competence = params.require(:competence)
      @competence = []
      competence['title'].each do |title_idx|
        @competence << Competence.new(title: title_idx.last,
          level: (competence['level'][title_idx.first] rescue nil)) unless title_idx.last.empty?
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :birthday, :function, :sex)
    end

    def set_selected_participants
      @selected_participants = session[:team_id] ?
        @team.team_participants.collect(&:participant) : []
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_competences.html.erb
<br />
<table>
  <thead>
    <tr>
      <th>Competência</th>
      <th>Básico</th>
      <th>Intermediário</th>
      <th>Avançado</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="competence-fields">
    <% @participant.competences.to_a.push(Competence.new(level:1)).each_with_index do |competence, index| %>
      <%= fields_for :competence, competence do |c| %>
        <tr>
          <td><%= c.text_field :title, class: 'competence-title', name: "competence[title][#{index}]" %></td>
          <td><%= c.radio_button :level, 1, name: "competence[level][#{index}]" %></td>
          <td><%= c.radio_button :level, 2, name: "competence[level][#{index}]" %></td>
          <td><%= c.radio_button :level, 3, name: "competence[level][#{index}]" %></td>
          <td><%= link_to 'Remover', '#', class: 'remove-competence-row' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br />
<script>
$('input.competence-title:last').val('').closest('tr');
$('a.remove-competence-row:last').css('visibility', 'hidden');
var next_row_index = $('tbody.competence-fields tr').size();
var $tbody = $('tbody.competence-fields');
$tbody.on('keydown keypress keyup', 'input.competence-title:last', function(){
  var $this = $(this);
  if($this.val() == '') {
    var $virtual_tr = $this.closest('tr').clone();
    $virtual_tr.html($virtual_tr.html().replace(/\[\d+\]/g,'['+next_row_index+']'));
    next_row_index++;
    $virtual_tr.appendTo($this.closest('tbody'));
    $this.closest('tr').find('a.remove-competence-row').css('visibility', 'visible');
  }
}).on('click', 'a.remove-competence-row', function(e){
  e.preventDefault();
  $(this).closest('tr').remove();
});
</script>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team.errors.count, "erro") %> impede este time de ser gravado:</h2>
      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, 'Nome Completo:' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthday, 'Data de Nascimento:' %>
    <%= f.text_field :birthday, value: @participant.birthday_verbose %>
  </div>
  <%= render 'competences' %>
  <div class="field">
    <%= f.label :function, 'Caso trabalhe, função que desempenha:' %>
    <%= f.text_field :function %>
  </div>
  <div class="field">
    <%= f.label :sex, 'Sexo:' %>
    <%= f.radio_button(:sex, "1") %>
    <%= f.label(:sex_1, "Masculino") %>
    <%= f.radio_button(:sex, "2") %>
    <%= f.label(:sex_2, "Feminino") %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar' %> |
    <%= link_to 'Voltar', participants_path %>
  </div>
<% end %>
<script type="text/javascript">
$("#participant_birthday").mask("?99/99/9999");
</script>

app/views/participants/_header.html.erb
<span><%= link_to 'Sair do experimento', teams_path %></span>
<% if(@selected_participants.size > 0) %>
	<span><%= link_to 'Concluir seleção de participantes', estimates_path %></span>
<% end %>
<br clear="both"/>
<br clear="both"/>

app/views/participants/_list.html.erb
<div style="float:left;margin-right:20px">
  <fieldset>
  <legend>Participantes do time "<%= @team.name %>"</legend>
    <table>
      <thead>
        <tr>
          <th>Integrante</th>
          <th>
            <% unless(hide_link_to_index rescue false) %>
              <%= link_to 'Mostrar lista de cadastrados', participants_path %>
            <% end %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @selected_participants.each do |participant| %>
          <tr>
            <td><%= participant.name %></td>
            <td><%= link_to 'Remover da lista', remove_from_list_participant_path(participant), data: { confirm: 'Tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </fieldset>
</div>

app/views/participants/add_to_list.html.erb
<%= render 'header' %>
<%= render 'list' %>
<fieldset>
  <legend>Tem certeza que deseja selecionar este participante?</legend>
  <p>
    <strong>Nome:</strong>
    <%= @participant.name %>
  </p>

  <p>
    <strong>Data de Nascimento:</strong>
    <%= @participant.birthday_verbose %>
  </p>

  <p>
    <table>
      <thead>
        <tr>
          <th>Competência</th>
          <th>Nível</th>
        </tr>
      </thead>
      <tbody class="competence-fields">
        <% @participant.competences.each do |competence| %>
          <tr>
            <td><%= competence.title %></td>
            <td><%= competence.level_verbose %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </p>

  <p>
    <strong>Caso trabalhe, função que desempenha:</strong>
    <%= @participant.function %>
  </p>

  <p>
    <strong>Sexo:</strong>
    <%= @participant.sex_verbose %>
  </p>

  <%= link_to 'Selecionar', confirm_add_to_list_participant_path(@participant) %> |
  <%= link_to 'Editar', edit_participant_path(@participant) %> |
  <%= link_to 'Voltar', participants_path %>
</fieldset>

app/views/participants/edit.html.erb
<%= render 'header' %>
<%= render 'list' %>
<fieldset>
  <legend>Participante <%= @selected_participants.size + 1 rescue 1 %></legend>
  <%= render 'form' %>
</fieldset>

app/views/participants/index.html.erb
<%= render 'header' %>
<%= render partial: 'list', locals: {hide_link_to_index: true} %>
<fieldset>
  <legend>Escolha um participante cadastrado ou realize um novo cadastro</legend>
  <table>
    <thead>
      <tr>
        <th>Participante cadastrado</th>
        <th><%= link_to 'Novo Participante', new_participant_path %></th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= link_to 'Selecionar', add_to_list_participant_path(participant) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br />
</fieldset>

app/views/participants/new.html.erb
<%= render 'header' %>
<%= render 'list' %>
<fieldset>
  <legend>Participante <%= @selected_participants.count + 1 %></legend>
  <%= render 'form' %>
</fieldset>