config/routes.rb
Rails.application.routes.draw do
  get 'reports/comparation_table'

  resources :requirements do
    collection do
      post 'search'
    end
  end

  post 'browser_logs/create'

  resources :teams
  root :to => 'teams#index'

  resources :estimates do
    collection do
      post 'create_round'
    end
  end

  resources :participants do
    member do
      get 'add_to_list'
      get 'confirm_add_to_list'
      get 'remove_from_list'
    end
  end

  resources :rounds

end

app/models/access_log.rb
class AccessLog < ActiveRecord::Base
end

app/models/browser_log.rb
class BrowserLog < ActiveRecord::Base
  belongs_to :access_log
end

app/models/competence.rb
class Competence < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :participant
  validates_presence_of :title
  validates_presence_of :level

  def level_verbose
    case level
      when 1 then 'Básico'
      when 2 then 'Intermediário'
      when 3 then 'Avançado'
      else ''
    end
  end
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :team
  belongs_to :requirement
  has_many :rounds
  validates :effort_estimate, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :justification, presence: true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  acts_as_paranoid
  has_many :competences
  has_many :round_participants
  has_many :rounds, through: :round_participants
  has_many :team_participants
  has_many :teams, through: :team_participants
  validates :name, presence: true
  validates :sex, presence: true
  validates :competences, presence: true
  validates :birthday, timeliness: { before: lambda{Date.current}, type: :date }

  def sex_verbose
    case sex
      when 1 then 'Masculino'
      when 2 then 'Feminino'
      else ''
    end
  end

  def birthday_verbose
  	self.birthday.strftime("%d/%m/%Y") rescue ''
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_paranoid
  has_many :requirements
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :project
  has_many :estimates

  def ar estimate
    (self.real_effort - estimate).abs
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :estimate
  has_many :round_participants
  validates :estimate, presence: true
  validates :number, presence: true
end

app/models/round_participant.rb
class RoundParticipant < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :participant
  belongs_to :round
  validates :participant, presence: true
  validates :round, presence: true
  validates :effort_estimate, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :justification, presence: true
end

app/models/team.rb
class Team < ActiveRecord::Base
  acts_as_paranoid
  has_many :team_participants
  has_many :participants, through: :team_participants
  validates :name, presence: true, uniqueness: true
end

app/models/team_participant.rb
class TeamParticipant < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :participant
  belongs_to :team
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browser_logs_helper.rb
module BrowserLogsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlanningpokerExperiment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script>
var last_event_captured_timestamp = null,
  last_event_captured_type = null,
  events_pool = [],
  get_attributes = function(obj, level){
    var values = new Object();
    for (key in obj) {
      try {
        if (key != 'delegateTarget' && obj.hasOwnProperty(key) && (typeof obj[key] !== 'undefined') && (typeof obj[key] !== 'function')){
          if(typeof obj[key] === 'object'){
            if(level < 1)
              values[key] = get_attributes(obj[key], level+1);
          } else {
            values[key] = obj[key];
          }
        }
      } catch(e) {}
    }
    return values;
  };

jQuery('body').on('click focus hover input paste keypress submit', '*', function(e){
  if(last_event_captured_timestamp != e.timeStamp || last_event_captured_type != e.type) {
    last_event_captured_timestamp = e.timeStamp;
    last_event_captured_type = e.type;
    events_pool.push(JSON.stringify(new get_attributes(e, 0)));
    if(events_pool.length >= 20 || e.type == 'submit' || e.type == 'click') {
      $.post('<%= browser_logs_create_path %>', {events_jsons: events_pool});
      delete(events_pool);
      events_pool = [];
    }
  }
});
</script>
</body>
</html>